language: ruby
sudo: false
cache: bundler
rvm:
  - "1.9.3"
  - "2.0"
  - "2.1"
  - "2.2"
  - "2.3.3"
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - gem update bundler
script:
  - bundle exec rspec
